# Generated by Django 4.1.4 on 2022-12-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="idClient",
            new_name="Client",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="idStaff",
            new_name="Staff",
        ),
    ]
