# Generated by Django 4.1.4 on 2022-12-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_idclient_service_client_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="Client",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="Staff",
            new_name="staff",
        ),
    ]
