# Generated by Django 4.1.4 on 2022-12-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clients",
            new_name="Client",
        ),
    ]
